// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai-providers": {
            "get": {
                "description": "分页查询 AI 提供商列表，列表不返回 API Key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai-provider"
                ],
                "summary": "查询 AI 提供商列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10，最大 100",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/aiprovider.aiProviderListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "post": {
                "description": "创建 AI 提供商，API Key 入库前会加密",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai-provider"
                ],
                "summary": "新增 AI 提供商",
                "parameters": [
                    {
                        "description": "AI 提供商信息",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/aiprovider.createAIProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/aiprovider.aiProviderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/ai-providers/{id}": {
            "get": {
                "description": "按 ID 查询 AI 提供商详情，返回解密后的 API Key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai-provider"
                ],
                "summary": "查询 AI 提供商详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AI 提供商 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/aiprovider.aiProviderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "AI 提供商不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "put": {
                "description": "按 ID 局部更新 AI 提供商，传入 API Key 时重新加密",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai-provider"
                ],
                "summary": "更新 AI 提供商",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AI 提供商 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AI 提供商信息",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/aiprovider.updateAIProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/aiprovider.aiProviderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "AI 提供商不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "delete": {
                "description": "按 ID 物理删除 AI 提供商",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai-provider"
                ],
                "summary": "删除 AI 提供商",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "AI 提供商 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "AI 提供商不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "登陆接口，只需要接受密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "登陆接口",
                "parameters": [
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/login.passwordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code = 0，表示登陆成功; code = 1000，表示没有初始密码,登陆失败",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/login/initial-password": {
            "get": {
                "description": "检查管理员初始化密码是否已经设置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "检查初始化密码",
                "responses": {
                    "200": {
                        "description": "code = 0 表示检查成功;data.initialized 表示是否已设置初始化密码",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "boolean"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/login/password": {
            "post": {
                "description": "仅在管理员密码为空时允许设置初始化密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "设置初始化密码",
                "parameters": [
                    {
                        "description": "Password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/login.passwordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code = 0，表示设置成功;code = 1001，表示密码已设置",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/novels": {
            "get": {
                "description": "分页查询小说列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "novel"
                ],
                "summary": "查询小说列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10，最大 100",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.novelListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "post": {
                "description": "创建小说，仅书名必填",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "novel"
                ],
                "summary": "新增小说",
                "parameters": [
                    {
                        "description": "小说信息",
                        "name": "novel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.createNovelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.novelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/novels/update": {
            "put": {
                "description": "按 ID 局部更新小说",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "novel"
                ],
                "summary": "更新小说",
                "parameters": [
                    {
                        "description": "小说信息",
                        "name": "novel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.updateNovelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.novelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/novels/{id}": {
            "get": {
                "description": "按 ID 查询单本小说",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "novel"
                ],
                "summary": "查询小说详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.novelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "delete": {
                "description": "按 ID 软删除小说",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "novel"
                ],
                "summary": "删除小说",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/novels/{id}/chapters": {
            "get": {
                "description": "分页查询指定小说的章节列表，列表不返回章节正文",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chapter"
                ],
                "summary": "查询章节列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10，最大 100",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.chapterListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "post": {
                "description": "给指定小说新增章节，并同步增加小说总字数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chapter"
                ],
                "summary": "新增章节",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "章节信息",
                        "name": "chapter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.createChapterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.chapterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "409": {
                        "description": "章节编号已存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/novels/{id}/chapters/next-no": {
            "get": {
                "description": "返回指定小说当前最大章节编号加一",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chapter"
                ],
                "summary": "查询下一章编号",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.nextChapterNoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/novels/{id}/chapters/{chapterId}": {
            "get": {
                "description": "查询指定小说下的章节详情，返回完整正文",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chapter"
                ],
                "summary": "查询章节详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "章节 ID",
                        "name": "chapterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.chapterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "章节不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "put": {
                "description": "局部更新章节，并按章节字数差值同步小说总字数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chapter"
                ],
                "summary": "修改章节",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "章节 ID",
                        "name": "chapterId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "章节信息",
                        "name": "chapter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.updateChapterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.chapterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "章节不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "409": {
                        "description": "章节编号已存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "delete": {
                "description": "软删除章节，并扣减小说总字数",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chapter"
                ],
                "summary": "删除章节",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "章节 ID",
                        "name": "chapterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "章节不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/novels/{id}/characters": {
            "get": {
                "description": "分页查询指定小说的角色列表，列表只返回角色名、性别、图像 URL、状态和标签",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "character"
                ],
                "summary": "查询角色列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10，最大 100",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.characterListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "post": {
                "description": "给指定小说新增角色资料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "character"
                ],
                "summary": "新增角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色信息",
                        "name": "character",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.createCharacterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.characterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "小说不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/novels/{id}/characters/{characterId}": {
            "get": {
                "description": "查询指定小说下的角色完整资料",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "character"
                ],
                "summary": "查询角色详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "角色 ID",
                        "name": "characterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.characterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "角色不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "put": {
                "description": "局部更新指定小说下的角色资料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "character"
                ],
                "summary": "修改角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "角色 ID",
                        "name": "characterId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色信息",
                        "name": "character",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novel.updateCharacterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/novel.characterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "角色不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            },
            "delete": {
                "description": "软删除指定小说下的角色",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "character"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "小说 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "角色 ID",
                        "name": "characterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "角色不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "使用 S3 兼容对象存储上传文件，返回公开访问地址",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/upload.uploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "系统错误",
                        "schema": {
                            "$ref": "#/definitions/common.SystemError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "aiprovider.aiProviderListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/aiprovider.aiProviderResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "aiprovider.aiProviderResponse": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "description": "API Key 明文，仅详情类响应返回",
                    "type": "string"
                },
                "baseUrl": {
                    "description": "AI 提供商基础 URL",
                    "type": "string"
                },
                "configJson": {
                    "description": "AI 提供商额外配置",
                    "type": "object"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "AI 提供商 ID",
                    "type": "integer"
                },
                "isEnabled": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "name": {
                    "description": "AI 提供商名称",
                    "type": "string"
                },
                "priority": {
                    "description": "优先级",
                    "type": "integer"
                },
                "providerType": {
                    "description": "AI 提供商类型",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "aiprovider.createAIProviderRequest": {
            "type": "object",
            "required": [
                "apiKey",
                "baseUrl",
                "name",
                "providerType"
            ],
            "properties": {
                "apiKey": {
                    "description": "API Key 明文，必填，入库前会加密",
                    "type": "string"
                },
                "baseUrl": {
                    "description": "AI 提供商基础 URL，必填",
                    "type": "string"
                },
                "configJson": {
                    "description": "AI 提供商额外配置",
                    "type": "object"
                },
                "isEnabled": {
                    "description": "是否启用；不传时默认 true",
                    "type": "boolean"
                },
                "name": {
                    "description": "AI 提供商名称，必填",
                    "type": "string"
                },
                "priority": {
                    "description": "优先级；不传时默认 100",
                    "type": "integer"
                },
                "providerType": {
                    "description": "AI 提供商类型，必填",
                    "type": "string"
                }
            }
        },
        "aiprovider.updateAIProviderRequest": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "description": "API Key 明文；传入时重新加密，不传则保留原值",
                    "type": "string"
                },
                "baseUrl": {
                    "description": "AI 提供商基础 URL",
                    "type": "string"
                },
                "configJson": {
                    "description": "AI 提供商额外配置",
                    "type": "object"
                },
                "isEnabled": {
                    "description": "是否启用",
                    "type": "boolean"
                },
                "name": {
                    "description": "AI 提供商名称",
                    "type": "string"
                },
                "priority": {
                    "description": "优先级",
                    "type": "integer"
                },
                "providerType": {
                    "description": "AI 提供商类型",
                    "type": "string"
                }
            }
        },
        "common.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "状态描述",
                    "type": "string"
                }
            }
        },
        "common.SystemError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code 是业务错误码，统一写入响应体，方便前端按业务场景处理。",
                    "type": "integer"
                },
                "msg": {
                    "description": "Msg 是展示给调用方的错误提示，保持和业务错误定义在同一处维护。",
                    "type": "string"
                }
            }
        },
        "login.passwordRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "novel.chapterListItemResponse": {
            "type": "object",
            "properties": {
                "chapterNo": {
                    "description": "章节编号",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "章节 ID",
                    "type": "integer"
                },
                "novelId": {
                    "description": "小说 ID",
                    "type": "integer"
                },
                "title": {
                    "description": "章节标题",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                },
                "wordCount": {
                    "description": "章节字数",
                    "type": "integer"
                }
            }
        },
        "novel.chapterListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/novel.chapterListItemResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "novel.chapterResponse": {
            "type": "object",
            "properties": {
                "chapterNo": {
                    "description": "章节编号",
                    "type": "integer"
                },
                "content": {
                    "description": "章节内容",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "章节 ID",
                    "type": "integer"
                },
                "novelId": {
                    "description": "小说 ID",
                    "type": "integer"
                },
                "title": {
                    "description": "章节标题",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                },
                "wordCount": {
                    "description": "章节字数",
                    "type": "integer"
                }
            }
        },
        "novel.characterListItemResponse": {
            "type": "object",
            "properties": {
                "appearanceImgUrl": {
                    "description": "角色形象图 URL",
                    "type": "string"
                },
                "charactersTags": {
                    "description": "角色标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "gender": {
                    "description": "角色性别",
                    "type": "string"
                },
                "id": {
                    "description": "角色 ID",
                    "type": "integer"
                },
                "name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "status": {
                    "description": "角色状态：1 在线，2 下线",
                    "type": "integer"
                }
            }
        },
        "novel.characterListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/novel.characterListItemResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "novel.characterResponse": {
            "type": "object",
            "properties": {
                "ability": {
                    "description": "角色能力",
                    "type": "string"
                },
                "appearance": {
                    "description": "角色外貌",
                    "type": "string"
                },
                "appearanceImgUrl": {
                    "description": "角色形象图 URL",
                    "type": "string"
                },
                "background": {
                    "description": "角色背景",
                    "type": "string"
                },
                "charactersTags": {
                    "description": "角色标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "firstAppearanceChapterId": {
                    "description": "首次出现章节 ID",
                    "type": "integer"
                },
                "gender": {
                    "description": "角色性别",
                    "type": "string"
                },
                "id": {
                    "description": "角色 ID",
                    "type": "integer"
                },
                "intro": {
                    "description": "角色介绍",
                    "type": "string"
                },
                "motivation": {
                    "description": "角色动机",
                    "type": "string"
                },
                "name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "novelId": {
                    "description": "小说 ID",
                    "type": "integer"
                },
                "personality": {
                    "description": "角色性格",
                    "type": "string"
                },
                "plotDirection": {
                    "description": "角色剧情方向",
                    "type": "string"
                },
                "status": {
                    "description": "角色状态：1 在线，2 下线",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "novel.createChapterRequest": {
            "type": "object",
            "required": [
                "chapterNo",
                "content",
                "title",
                "wordCount"
            ],
            "properties": {
                "chapterNo": {
                    "description": "章节编号，必填且大于 0",
                    "type": "integer"
                },
                "content": {
                    "description": "章节内容，必填",
                    "type": "string"
                },
                "title": {
                    "description": "章节标题，必填",
                    "type": "string"
                },
                "wordCount": {
                    "description": "章节字数，必填；用指针是为了允许前端传 0",
                    "type": "integer"
                }
            }
        },
        "novel.createCharacterRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "ability": {
                    "description": "角色能力",
                    "type": "string"
                },
                "appearance": {
                    "description": "角色外貌",
                    "type": "string"
                },
                "appearanceImgUrl": {
                    "description": "角色形象图 URL",
                    "type": "string"
                },
                "background": {
                    "description": "角色背景",
                    "type": "string"
                },
                "charactersTags": {
                    "description": "角色标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "firstAppearanceChapterId": {
                    "description": "首次出现章节 ID",
                    "type": "integer"
                },
                "gender": {
                    "description": "角色性别",
                    "type": "string"
                },
                "intro": {
                    "description": "角色介绍",
                    "type": "string"
                },
                "motivation": {
                    "description": "角色动机",
                    "type": "string"
                },
                "name": {
                    "description": "角色名称，必填",
                    "type": "string"
                },
                "personality": {
                    "description": "角色性格",
                    "type": "string"
                },
                "plotDirection": {
                    "description": "角色剧情方向",
                    "type": "string"
                },
                "status": {
                    "description": "角色状态：1 在线，2 下线",
                    "type": "integer"
                }
            }
        },
        "novel.createNovelRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "authorName": {
                    "description": "小说作者",
                    "type": "string"
                },
                "coverUrl": {
                    "description": "小说封面 URL",
                    "type": "string"
                },
                "intro": {
                    "description": "小说简介",
                    "type": "string"
                },
                "metadata": {
                    "description": "小说元数据（标签信息）",
                    "type": "object"
                },
                "title": {
                    "description": "书名，必填",
                    "type": "string"
                }
            }
        },
        "novel.nextChapterNoResponse": {
            "type": "object",
            "properties": {
                "chapterNo": {
                    "type": "integer"
                }
            }
        },
        "novel.novelListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/novel.novelResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "novel.novelResponse": {
            "type": "object",
            "properties": {
                "authorName": {
                    "description": "小说作者",
                    "type": "string"
                },
                "coverUrl": {
                    "description": "小说封面 URL",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "小说 ID",
                    "type": "integer"
                },
                "intro": {
                    "description": "小说简介",
                    "type": "string"
                },
                "metadata": {
                    "description": "小说元数据（标签信息）",
                    "type": "object"
                },
                "title": {
                    "description": "书名",
                    "type": "string"
                },
                "wordCount": {
                    "description": "小说字数",
                    "type": "integer"
                }
            }
        },
        "novel.updateChapterRequest": {
            "type": "object",
            "properties": {
                "chapterNo": {
                    "description": "章节编号",
                    "type": "integer"
                },
                "content": {
                    "description": "章节内容",
                    "type": "string"
                },
                "title": {
                    "description": "章节标题",
                    "type": "string"
                },
                "wordCount": {
                    "description": "章节字数",
                    "type": "integer"
                }
            }
        },
        "novel.updateCharacterRequest": {
            "type": "object",
            "properties": {
                "ability": {
                    "description": "角色能力",
                    "type": "string"
                },
                "appearance": {
                    "description": "角色外貌",
                    "type": "string"
                },
                "appearanceImgUrl": {
                    "description": "角色形象图 URL",
                    "type": "string"
                },
                "background": {
                    "description": "角色背景",
                    "type": "string"
                },
                "charactersTags": {
                    "description": "角色标签；使用指针用于区分“未传”和“传空数组”",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "firstAppearanceChapterId": {
                    "description": "首次出现章节 ID",
                    "type": "integer"
                },
                "gender": {
                    "description": "角色性别",
                    "type": "string"
                },
                "intro": {
                    "description": "角色介绍",
                    "type": "string"
                },
                "motivation": {
                    "description": "角色动机",
                    "type": "string"
                },
                "name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "personality": {
                    "description": "角色性格",
                    "type": "string"
                },
                "plotDirection": {
                    "description": "角色剧情方向",
                    "type": "string"
                },
                "status": {
                    "description": "角色状态：1 在线，2 下线",
                    "type": "integer"
                }
            }
        },
        "novel.updateNovelRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "authorName": {
                    "description": "小说作者",
                    "type": "string"
                },
                "coverUrl": {
                    "description": "小说封面 URL",
                    "type": "string"
                },
                "id": {
                    "description": "小说 ID，必填",
                    "type": "integer"
                },
                "intro": {
                    "description": "小说简介",
                    "type": "string"
                },
                "metadata": {
                    "description": "小说元数据（标签信息）",
                    "type": "object"
                },
                "title": {
                    "description": "书名",
                    "type": "string"
                }
            }
        },
        "upload.uploadResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "Key 文件在 S3/对象存储桶里的对象路径，相当于存储内部的文件名",
                    "type": "string"
                },
                "url": {
                    "description": "URL 前端可以直接访问的公开地址，是用配置里的 public_base_url 加上 key 拼出来的",
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "AI小说系统接口文档",
	Description:      "AI小说系统接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
